#include "misc.hpp"

namespace gp::sdl::internal {
misc::Event::ScanCode to_scan_code(const SDL_Scancode sdl_scan_code) {
  switch (sdl_scan_code) {
  case SDL_SCANCODE_A:
    return misc::Event::ScanCode::A;
  case SDL_SCANCODE_B:
    return misc::Event::ScanCode::B;
  case SDL_SCANCODE_C:
    return misc::Event::ScanCode::C;
  case SDL_SCANCODE_D:
    return misc::Event::ScanCode::D;
  case SDL_SCANCODE_E:
    return misc::Event::ScanCode::E;
  case SDL_SCANCODE_F:
    return misc::Event::ScanCode::F;
  case SDL_SCANCODE_G:
    return misc::Event::ScanCode::G;
  case SDL_SCANCODE_H:
    return misc::Event::ScanCode::H;
  case SDL_SCANCODE_I:
    return misc::Event::ScanCode::I;
  case SDL_SCANCODE_J:
    return misc::Event::ScanCode::J;
  case SDL_SCANCODE_K:
    return misc::Event::ScanCode::K;
  case SDL_SCANCODE_L:
    return misc::Event::ScanCode::L;
  case SDL_SCANCODE_M:
    return misc::Event::ScanCode::M;
  case SDL_SCANCODE_N:
    return misc::Event::ScanCode::N;
  case SDL_SCANCODE_O:
    return misc::Event::ScanCode::O;
  case SDL_SCANCODE_P:
    return misc::Event::ScanCode::P;
  case SDL_SCANCODE_Q:
    return misc::Event::ScanCode::Q;
  case SDL_SCANCODE_R:
    return misc::Event::ScanCode::R;
  case SDL_SCANCODE_S:
    return misc::Event::ScanCode::S;
  case SDL_SCANCODE_T:
    return misc::Event::ScanCode::T;
  case SDL_SCANCODE_U:
    return misc::Event::ScanCode::U;
  case SDL_SCANCODE_V:
    return misc::Event::ScanCode::V;
  case SDL_SCANCODE_W:
    return misc::Event::ScanCode::W;
  case SDL_SCANCODE_X:
    return misc::Event::ScanCode::X;
  case SDL_SCANCODE_Y:
    return misc::Event::ScanCode::Y;
  case SDL_SCANCODE_Z:
    return misc::Event::ScanCode::Z;
  case SDL_SCANCODE_0:
    return misc::Event::ScanCode::Number0;
  case SDL_SCANCODE_1:
    return misc::Event::ScanCode::Number1;
  case SDL_SCANCODE_2:
    return misc::Event::ScanCode::Number2;
  case SDL_SCANCODE_3:
    return misc::Event::ScanCode::Number3;
  case SDL_SCANCODE_4:
    return misc::Event::ScanCode::Number4;
  case SDL_SCANCODE_5:
    return misc::Event::ScanCode::Number5;
  case SDL_SCANCODE_6:
    return misc::Event::ScanCode::Number6;
  case SDL_SCANCODE_7:
    return misc::Event::ScanCode::Number7;
  case SDL_SCANCODE_8:
    return misc::Event::ScanCode::Number8;
  case SDL_SCANCODE_9:
    return misc::Event::ScanCode::Number9;
  case SDL_SCANCODE_F1:
    return misc::Event::ScanCode::F1;
  case SDL_SCANCODE_F2:
    return misc::Event::ScanCode::F2;
  case SDL_SCANCODE_F3:
    return misc::Event::ScanCode::F3;
  case SDL_SCANCODE_F4:
    return misc::Event::ScanCode::F4;
  case SDL_SCANCODE_F5:
    return misc::Event::ScanCode::F5;
  case SDL_SCANCODE_F6:
    return misc::Event::ScanCode::F6;
  case SDL_SCANCODE_F7:
    return misc::Event::ScanCode::F7;
  case SDL_SCANCODE_F8:
    return misc::Event::ScanCode::F8;
  case SDL_SCANCODE_F9:
    return misc::Event::ScanCode::F9;
  case SDL_SCANCODE_F10:
    return misc::Event::ScanCode::F10;
  case SDL_SCANCODE_F11:
    return misc::Event::ScanCode::F11;
  case SDL_SCANCODE_F12:
    return misc::Event::ScanCode::F12;
  case SDL_SCANCODE_F13:
    return misc::Event::ScanCode::F13;
  case SDL_SCANCODE_F14:
    return misc::Event::ScanCode::F14;
  case SDL_SCANCODE_F15:
    return misc::Event::ScanCode::F15;
  case SDL_SCANCODE_F16:
    return misc::Event::ScanCode::F16;
  case SDL_SCANCODE_F17:
    return misc::Event::ScanCode::F17;
  case SDL_SCANCODE_F18:
    return misc::Event::ScanCode::F18;
  case SDL_SCANCODE_F19:
    return misc::Event::ScanCode::F19;
  case SDL_SCANCODE_F20:
    return misc::Event::ScanCode::F20;
  case SDL_SCANCODE_F21:
    return misc::Event::ScanCode::F21;
  case SDL_SCANCODE_F22:
    return misc::Event::ScanCode::F22;
  case SDL_SCANCODE_F23:
    return misc::Event::ScanCode::F23;
  case SDL_SCANCODE_F24:
    return misc::Event::ScanCode::F24;
  case SDL_SCANCODE_AC_BACK:
    return misc::Event::ScanCode::ApplicationControlKeypadBack;
  case SDL_SCANCODE_AC_BOOKMARKS:
    return misc::Event::ScanCode::ApplicationControlKeypadBookmarks;
  case SDL_SCANCODE_AC_FORWARD:
    return misc::Event::ScanCode::ApplicationControlKeypadForward;
  case SDL_SCANCODE_AC_HOME:
    return misc::Event::ScanCode::ApplicationControlKeypadHome;
  case SDL_SCANCODE_AC_REFRESH:
    return misc::Event::ScanCode::ApplicationControlKeypadRefresh;
  case SDL_SCANCODE_AC_SEARCH:
    return misc::Event::ScanCode::ApplicationControlKeypadSearch;
  case SDL_SCANCODE_AC_STOP:
    return misc::Event::ScanCode::ApplicationControlKeypadStop;
  case SDL_SCANCODE_AGAIN:
    return misc::Event::ScanCode::Again;
  case SDL_SCANCODE_ALTERASE:
    return misc::Event::ScanCode::AltErase;
  case SDL_SCANCODE_APOSTROPHE:
    return misc::Event::ScanCode::Apostrophe;
  case SDL_SCANCODE_APPLICATION:
    return misc::Event::ScanCode::Application;
  case SDL_SCANCODE_AUDIOMUTE:
    return misc::Event::ScanCode::AudioMute;
  case SDL_SCANCODE_AUDIONEXT:
    return misc::Event::ScanCode::AudioNext;
  case SDL_SCANCODE_AUDIOPLAY:
    return misc::Event::ScanCode::AudioPlay;
  case SDL_SCANCODE_AUDIOPREV:
    return misc::Event::ScanCode::AudioPrev;
  case SDL_SCANCODE_AUDIOSTOP:
    return misc::Event::ScanCode::AudioStop;
  case SDL_SCANCODE_BACKSLASH:
    return misc::Event::ScanCode::Backslash;
  case SDL_SCANCODE_BACKSPACE:
    return misc::Event::ScanCode::Backspace;
  case SDL_SCANCODE_BRIGHTNESSDOWN:
    return misc::Event::ScanCode::BrightnessDown;
  case SDL_SCANCODE_BRIGHTNESSUP:
    return misc::Event::ScanCode::BrightnessUp;
  case SDL_SCANCODE_CALCULATOR:
    return misc::Event::ScanCode::Calculator;
  case SDL_SCANCODE_CANCEL:
    return misc::Event::ScanCode::Cancel;
  case SDL_SCANCODE_CAPSLOCK:
    return misc::Event::ScanCode::CapsLock;
  case SDL_SCANCODE_CLEAR:
    return misc::Event::ScanCode::Clear;
  case SDL_SCANCODE_CLEARAGAIN:
    return misc::Event::ScanCode::ClearAgain;
  case SDL_SCANCODE_COMMA:
    return misc::Event::ScanCode::Comma;
  case SDL_SCANCODE_COMPUTER:
    return misc::Event::ScanCode::Computer;
  case SDL_SCANCODE_COPY:
    return misc::Event::ScanCode::Copy;
  case SDL_SCANCODE_CRSEL:
    return misc::Event::ScanCode::CrSel;
  case SDL_SCANCODE_CURRENCYSUBUNIT:
    return misc::Event::ScanCode::CurrencySubUnit;
  case SDL_SCANCODE_CURRENCYUNIT:
    return misc::Event::ScanCode::CurrencyUnit;
  case SDL_SCANCODE_CUT:
    return misc::Event::ScanCode::Cut;
  case SDL_SCANCODE_DECIMALSEPARATOR:
    return misc::Event::ScanCode::DecimalSeparator;
  case SDL_SCANCODE_DELETE:
    return misc::Event::ScanCode::Delete;
  case SDL_SCANCODE_DISPLAYSWITCH:
    return misc::Event::ScanCode::DisplaySwitch;
  case SDL_SCANCODE_DOWN:
    return misc::Event::ScanCode::Down;
  case SDL_SCANCODE_EJECT:
    return misc::Event::ScanCode::Eject;
  case SDL_SCANCODE_END:
    return misc::Event::ScanCode::End;
  case SDL_SCANCODE_EQUALS:
    return misc::Event::ScanCode::Equals;
  case SDL_SCANCODE_ESCAPE:
    return misc::Event::ScanCode::Escape;
  case SDL_SCANCODE_EXECUTE:
    return misc::Event::ScanCode::Execute;
  case SDL_SCANCODE_EXSEL:
    return misc::Event::ScanCode::ExSel;
  case SDL_SCANCODE_FIND:
    return misc::Event::ScanCode::Find;
  case SDL_SCANCODE_GRAVE:
    return misc::Event::ScanCode::Grave;
  case SDL_SCANCODE_HELP:
    return misc::Event::ScanCode::Help;
  case SDL_SCANCODE_HOME:
    return misc::Event::ScanCode::Home;
  case SDL_SCANCODE_INSERT:
    return misc::Event::ScanCode::Insert;
  case SDL_SCANCODE_KBDILLUMDOWN:
    return misc::Event::ScanCode::KeyboardIlluminationDown;
  case SDL_SCANCODE_KBDILLUMTOGGLE:
    return misc::Event::ScanCode::KeyboardIlluminationToggle;
  case SDL_SCANCODE_KBDILLUMUP:
    return misc::Event::ScanCode::KeyboardIlluminationUp;
  case SDL_SCANCODE_KP_0:
    return misc::Event::ScanCode::NumericKeypad0;
  case SDL_SCANCODE_KP_1:
    return misc::Event::ScanCode::NumericKeypad1;
  case SDL_SCANCODE_KP_2:
    return misc::Event::ScanCode::NumericKeypad2;
  case SDL_SCANCODE_KP_3:
    return misc::Event::ScanCode::NumericKeypad3;
  case SDL_SCANCODE_KP_4:
    return misc::Event::ScanCode::NumericKeypad4;
  case SDL_SCANCODE_KP_5:
    return misc::Event::ScanCode::NumericKeypad5;
  case SDL_SCANCODE_KP_6:
    return misc::Event::ScanCode::NumericKeypad6;
  case SDL_SCANCODE_KP_7:
    return misc::Event::ScanCode::NumericKeypad7;
  case SDL_SCANCODE_KP_8:
    return misc::Event::ScanCode::NumericKeypad8;
  case SDL_SCANCODE_KP_9:
    return misc::Event::ScanCode::NumericKeypad9;
  case SDL_SCANCODE_KP_A:
    return misc::Event::ScanCode::NumericKeypadA;
  case SDL_SCANCODE_KP_B:
    return misc::Event::ScanCode::NumericKeypadB;
  case SDL_SCANCODE_KP_C:
    return misc::Event::ScanCode::NumericKeypadC;
  case SDL_SCANCODE_KP_D:
    return misc::Event::ScanCode::NumericKeypadD;
  case SDL_SCANCODE_KP_E:
    return misc::Event::ScanCode::NumericKeypadE;
  case SDL_SCANCODE_KP_F:
    return misc::Event::ScanCode::NumericKeypadF;
  case SDL_SCANCODE_KP_00:
    return misc::Event::ScanCode::NumericKeypad00;
  case SDL_SCANCODE_KP_000:
    return misc::Event::ScanCode::NumericKeypad000;
  case SDL_SCANCODE_KP_AMPERSAND:
    return misc::Event::ScanCode::NumericKeypadAmpersand;
  case SDL_SCANCODE_KP_AT:
    return misc::Event::ScanCode::NumericKeypadAt;
  case SDL_SCANCODE_KP_BACKSPACE:
    return misc::Event::ScanCode::NumericKeypadBackspace;
  case SDL_SCANCODE_KP_BINARY:
    return misc::Event::ScanCode::NumericKeypadBinary;
  case SDL_SCANCODE_KP_CLEAR:
    return misc::Event::ScanCode::NumericKeypadClear;
  case SDL_SCANCODE_KP_CLEARENTRY:
    return misc::Event::ScanCode::NumericKeypadClearEntry;
  case SDL_SCANCODE_KP_COLON:
    return misc::Event::ScanCode::NumericKeypadColon;
  case SDL_SCANCODE_KP_COMMA:
    return misc::Event::ScanCode::NumericKeypadComma;
  case SDL_SCANCODE_KP_DBLAMPERSAND:
    return misc::Event::ScanCode::NumericKeypadDoubleAmpersand;
  case SDL_SCANCODE_KP_DBLVERTICALBAR:
    return misc::Event::ScanCode::NumericKeypadDoubleVerticalBar;
  case SDL_SCANCODE_KP_DECIMAL:
    return misc::Event::ScanCode::NumericKeypadDecimal;
  case SDL_SCANCODE_KP_DIVIDE:
    return misc::Event::ScanCode::NumericKeypadDivide;
  case SDL_SCANCODE_KP_ENTER:
    return misc::Event::ScanCode::NumericKeypadEnter;
  case SDL_SCANCODE_KP_EQUALS:
    return misc::Event::ScanCode::NumericKeypadEquals;
  case SDL_SCANCODE_KP_EQUALSAS400:
    return misc::Event::ScanCode::NumericKeypadEqualsAS400;
  case SDL_SCANCODE_KP_EXCLAM:
    return misc::Event::ScanCode::NumericKeypadExclam;
  case SDL_SCANCODE_KP_GREATER:
    return misc::Event::ScanCode::NumericKeypadGreater;
  case SDL_SCANCODE_KP_HASH:
    return misc::Event::ScanCode::NumericKeypadHash;
  case SDL_SCANCODE_KP_HEXADECIMAL:
    return misc::Event::ScanCode::NumericKeypadHexadecimal;
  case SDL_SCANCODE_KP_LEFTBRACE:
    return misc::Event::ScanCode::NumericKeypadLeftBrace;
  case SDL_SCANCODE_KP_LEFTPAREN:
    return misc::Event::ScanCode::NumericKeypadLeftParenthesis;
  case SDL_SCANCODE_KP_LESS:
    return misc::Event::ScanCode::NumericKeypadLess;
  case SDL_SCANCODE_KP_MEMADD:
    return misc::Event::ScanCode::NumericKeypadMemAdd;
  case SDL_SCANCODE_KP_MEMCLEAR:
    return misc::Event::ScanCode::NumericKeypadMemClear;
  case SDL_SCANCODE_KP_MEMDIVIDE:
    return misc::Event::ScanCode::NumericKeypadMemDivide;
  case SDL_SCANCODE_KP_MEMMULTIPLY:
    return misc::Event::ScanCode::NumericKeypadMemMultiply;
  case SDL_SCANCODE_KP_MEMRECALL:
    return misc::Event::ScanCode::NumericKeypadMemRecall;
  case SDL_SCANCODE_KP_MEMSTORE:
    return misc::Event::ScanCode::NumericKeypadMemStore;
  case SDL_SCANCODE_KP_MEMSUBTRACT:
    return misc::Event::ScanCode::NumericKeypadMemSubtract;
  case SDL_SCANCODE_KP_MINUS:
    return misc::Event::ScanCode::NumericKeypadMinus;
  case SDL_SCANCODE_KP_MULTIPLY:
    return misc::Event::ScanCode::NumericKeypadMultiply;
  case SDL_SCANCODE_KP_OCTAL:
    return misc::Event::ScanCode::NumericKeypadOctal;
  case SDL_SCANCODE_KP_PERCENT:
    return misc::Event::ScanCode::NumericKeypadPercent;
  case SDL_SCANCODE_KP_PERIOD:
    return misc::Event::ScanCode::NumericKeypadPeriod;
  case SDL_SCANCODE_KP_PLUS:
    return misc::Event::ScanCode::NumericKeypadPlus;
  case SDL_SCANCODE_KP_PLUSMINUS:
    return misc::Event::ScanCode::NumericKeypadPlusMinus;
  case SDL_SCANCODE_KP_POWER:
    return misc::Event::ScanCode::NumericKeypadPower;
  case SDL_SCANCODE_KP_RIGHTBRACE:
    return misc::Event::ScanCode::NumericKeypadRightBrace;
  case SDL_SCANCODE_KP_RIGHTPAREN:
    return misc::Event::ScanCode::NumericKeypadRightParenthesis;
  case SDL_SCANCODE_KP_SPACE:
    return misc::Event::ScanCode::NumericKeypadSpace;
  case SDL_SCANCODE_KP_TAB:
    return misc::Event::ScanCode::NumericKeypadTab;
  case SDL_SCANCODE_KP_VERTICALBAR:
    return misc::Event::ScanCode::NumericKeypadVerticalBar;
  case SDL_SCANCODE_KP_XOR:
    return misc::Event::ScanCode::NumericKeypadXOR;
  case SDL_SCANCODE_LALT:
    return misc::Event::ScanCode::LeftAlt;
  case SDL_SCANCODE_LCTRL:
    return misc::Event::ScanCode::LeftCtrl;
  case SDL_SCANCODE_LEFT:
    return misc::Event::ScanCode::Left;
  case SDL_SCANCODE_LEFTBRACKET:
    return misc::Event::ScanCode::LeftBracket;
  case SDL_SCANCODE_LGUI:
    return misc::Event::ScanCode::LeftGui;
  case SDL_SCANCODE_LSHIFT:
    return misc::Event::ScanCode::LeftShift;
  case SDL_SCANCODE_MAIL:
    return misc::Event::ScanCode::Mail;
  case SDL_SCANCODE_MEDIASELECT:
    return misc::Event::ScanCode::MediaSelect;
  case SDL_SCANCODE_MENU:
    return misc::Event::ScanCode::Menu;
  case SDL_SCANCODE_MINUS:
    return misc::Event::ScanCode::Minus;
  case SDL_SCANCODE_MODE:
    return misc::Event::ScanCode::ModeSwitch;
  case SDL_SCANCODE_MUTE:
    return misc::Event::ScanCode::Mute;
  case SDL_SCANCODE_NUMLOCKCLEAR:
    return misc::Event::ScanCode::NumLock;
  case SDL_SCANCODE_OPER:
    return misc::Event::ScanCode::Oper;
  case SDL_SCANCODE_OUT:
    return misc::Event::ScanCode::Out;
  case SDL_SCANCODE_PAGEDOWN:
    return misc::Event::ScanCode::PageDown;
  case SDL_SCANCODE_PAGEUP:
    return misc::Event::ScanCode::PageUp;
  case SDL_SCANCODE_PASTE:
    return misc::Event::ScanCode::Paste;
  case SDL_SCANCODE_PAUSE:
    return misc::Event::ScanCode::Pause;
  case SDL_SCANCODE_PERIOD:
    return misc::Event::ScanCode::Period;
  case SDL_SCANCODE_POWER:
    return misc::Event::ScanCode::Power;
  case SDL_SCANCODE_PRINTSCREEN:
    return misc::Event::ScanCode::PrintScreen;
  case SDL_SCANCODE_PRIOR:
    return misc::Event::ScanCode::Prior;
  case SDL_SCANCODE_RALT:
    return misc::Event::ScanCode::RightAlt;
  case SDL_SCANCODE_RCTRL:
    return misc::Event::ScanCode::RightCtrl;
  case SDL_SCANCODE_RETURN:
    return misc::Event::ScanCode::Enter;
  case SDL_SCANCODE_RETURN2:
    return misc::Event::ScanCode::Return;
  case SDL_SCANCODE_RGUI:
    return misc::Event::ScanCode::RightGui;
  case SDL_SCANCODE_RIGHT:
    return misc::Event::ScanCode::Right;
  case SDL_SCANCODE_RIGHTBRACKET:
    return misc::Event::ScanCode::RightBracket;
  case SDL_SCANCODE_RSHIFT:
    return misc::Event::ScanCode::RightShift;
  case SDL_SCANCODE_SCROLLLOCK:
    return misc::Event::ScanCode::ScrollLock;
  case SDL_SCANCODE_SELECT:
    return misc::Event::ScanCode::Select;
  case SDL_SCANCODE_SEMICOLON:
    return misc::Event::ScanCode::Semicolon;
  case SDL_SCANCODE_SEPARATOR:
    return misc::Event::ScanCode::Separator;
  case SDL_SCANCODE_SLASH:
    return misc::Event::ScanCode::Slash;
  case SDL_SCANCODE_SLEEP:
    return misc::Event::ScanCode::Sleep;
  case SDL_SCANCODE_SPACE:
    return misc::Event::ScanCode::Space;
  case SDL_SCANCODE_STOP:
    return misc::Event::ScanCode::Stop;
  case SDL_SCANCODE_SYSREQ:
    return misc::Event::ScanCode::SysReq;
  case SDL_SCANCODE_TAB:
    return misc::Event::ScanCode::Tab;
  case SDL_SCANCODE_THOUSANDSSEPARATOR:
    return misc::Event::ScanCode::ThousandsSeparator;
  case SDL_SCANCODE_UNDO:
    return misc::Event::ScanCode::Undo;
  case SDL_SCANCODE_UP:
    return misc::Event::ScanCode::Up;
  case SDL_SCANCODE_VOLUMEDOWN:
    return misc::Event::ScanCode::VolumeDown;
  case SDL_SCANCODE_VOLUMEUP:
    return misc::Event::ScanCode::VolumeUp;
  case SDL_SCANCODE_WWW:
    return misc::Event::ScanCode::WWW;
  default:
    return misc::Event::ScanCode::None;
  }
}
} // namespace gp::sdl::internal
