#include "misc.hpp"

#include <gp/glfw/glfw.hpp>

namespace gp::sdl::internal {
misc::Event::ScanCode to_scan_code(const int glfw_scan_code) {
  switch (glfw_scan_code) {
  case GLFW_KEY_A:
    return misc::Event::ScanCode::A;
  case GLFW_KEY_B:
    return misc::Event::ScanCode::B;
  case GLFW_KEY_C:
    return misc::Event::ScanCode::C;
  case GLFW_KEY_D:
    return misc::Event::ScanCode::D;
  case GLFW_KEY_E:
    return misc::Event::ScanCode::E;
  case GLFW_KEY_F:
    return misc::Event::ScanCode::F;
  case GLFW_KEY_G:
    return misc::Event::ScanCode::G;
  case GLFW_KEY_H:
    return misc::Event::ScanCode::H;
  case GLFW_KEY_I:
    return misc::Event::ScanCode::I;
  case GLFW_KEY_J:
    return misc::Event::ScanCode::J;
  case GLFW_KEY_K:
    return misc::Event::ScanCode::K;
  case GLFW_KEY_L:
    return misc::Event::ScanCode::L;
  case GLFW_KEY_M:
    return misc::Event::ScanCode::M;
  case GLFW_KEY_N:
    return misc::Event::ScanCode::N;
  case GLFW_KEY_O:
    return misc::Event::ScanCode::O;
  case GLFW_KEY_P:
    return misc::Event::ScanCode::P;
  case GLFW_KEY_Q:
    return misc::Event::ScanCode::Q;
  case GLFW_KEY_R:
    return misc::Event::ScanCode::R;
  case GLFW_KEY_S:
    return misc::Event::ScanCode::S;
  case GLFW_KEY_T:
    return misc::Event::ScanCode::T;
  case GLFW_KEY_U:
    return misc::Event::ScanCode::U;
  case GLFW_KEY_V:
    return misc::Event::ScanCode::V;
  case GLFW_KEY_W:
    return misc::Event::ScanCode::W;
  case GLFW_KEY_X:
    return misc::Event::ScanCode::X;
  case GLFW_KEY_Y:
    return misc::Event::ScanCode::Y;
  case GLFW_KEY_Z:
    return misc::Event::ScanCode::Z;
  case GLFW_KEY_0:
    return misc::Event::ScanCode::Number0;
  case GLFW_KEY_1:
    return misc::Event::ScanCode::Number1;
  case GLFW_KEY_2:
    return misc::Event::ScanCode::Number2;
  case GLFW_KEY_3:
    return misc::Event::ScanCode::Number3;
  case GLFW_KEY_4:
    return misc::Event::ScanCode::Number4;
  case GLFW_KEY_5:
    return misc::Event::ScanCode::Number5;
  case GLFW_KEY_6:
    return misc::Event::ScanCode::Number6;
  case GLFW_KEY_7:
    return misc::Event::ScanCode::Number7;
  case GLFW_KEY_8:
    return misc::Event::ScanCode::Number8;
  case GLFW_KEY_9:
    return misc::Event::ScanCode::Number9;
  case GLFW_KEY_F1:
    return misc::Event::ScanCode::F1;
  case GLFW_KEY_F2:
    return misc::Event::ScanCode::F2;
  case GLFW_KEY_F3:
    return misc::Event::ScanCode::F3;
  case GLFW_KEY_F4:
    return misc::Event::ScanCode::F4;
  case GLFW_KEY_F5:
    return misc::Event::ScanCode::F5;
  case GLFW_KEY_F6:
    return misc::Event::ScanCode::F6;
  case GLFW_KEY_F7:
    return misc::Event::ScanCode::F7;
  case GLFW_KEY_F8:
    return misc::Event::ScanCode::F8;
  case GLFW_KEY_F9:
    return misc::Event::ScanCode::F9;
  case GLFW_KEY_F10:
    return misc::Event::ScanCode::F10;
  case GLFW_KEY_F11:
    return misc::Event::ScanCode::F11;
  case GLFW_KEY_F12:
    return misc::Event::ScanCode::F12;
  case GLFW_KEY_F13:
    return misc::Event::ScanCode::F13;
  case GLFW_KEY_F14:
    return misc::Event::ScanCode::F14;
  case GLFW_KEY_F15:
    return misc::Event::ScanCode::F15;
  case GLFW_KEY_F16:
    return misc::Event::ScanCode::F16;
  case GLFW_KEY_F17:
    return misc::Event::ScanCode::F17;
  case GLFW_KEY_F18:
    return misc::Event::ScanCode::F18;
  case GLFW_KEY_F19:
    return misc::Event::ScanCode::F19;
  case GLFW_KEY_F20:
    return misc::Event::ScanCode::F20;
  case GLFW_KEY_F21:
    return misc::Event::ScanCode::F21;
  case GLFW_KEY_F22:
    return misc::Event::ScanCode::F22;
  case GLFW_KEY_F23:
    return misc::Event::ScanCode::F23;
  case GLFW_KEY_F24:
    return misc::Event::ScanCode::F24;
  case GLFW_KEY_APOSTROPHE:
    return misc::Event::ScanCode::Apostrophe;
  case GLFW_KEY_BACKSLASH:
    return misc::Event::ScanCode::Backslash;
  case GLFW_KEY_BACKSPACE:
    return misc::Event::ScanCode::Backspace;
  case GLFW_KEY_CAPS_LOCK:
    return misc::Event::ScanCode::CapsLock;
  case GLFW_KEY_COMMA:
    return misc::Event::ScanCode::Comma;
  case GLFW_KEY_DELETE:
    return misc::Event::ScanCode::Delete;
  case GLFW_KEY_DOWN:
    return misc::Event::ScanCode::Down;
  case GLFW_KEY_END:
    return misc::Event::ScanCode::End;
  case GLFW_KEY_EQUAL:
    return misc::Event::ScanCode::Equals;
  case GLFW_KEY_ESCAPE:
    return misc::Event::ScanCode::Escape;
  case GLFW_KEY_GRAVE_ACCENT:
    return misc::Event::ScanCode::Grave;
  case GLFW_KEY_HOME:
    return misc::Event::ScanCode::Home;
  case GLFW_KEY_INSERT:
    return misc::Event::ScanCode::Insert;
  case GLFW_KEY_KP_0:
    return misc::Event::ScanCode::NumericKeypad0;
  case GLFW_KEY_KP_1:
    return misc::Event::ScanCode::NumericKeypad1;
  case GLFW_KEY_KP_2:
    return misc::Event::ScanCode::NumericKeypad2;
  case GLFW_KEY_KP_3:
    return misc::Event::ScanCode::NumericKeypad3;
  case GLFW_KEY_KP_4:
    return misc::Event::ScanCode::NumericKeypad4;
  case GLFW_KEY_KP_5:
    return misc::Event::ScanCode::NumericKeypad5;
  case GLFW_KEY_KP_6:
    return misc::Event::ScanCode::NumericKeypad6;
  case GLFW_KEY_KP_7:
    return misc::Event::ScanCode::NumericKeypad7;
  case GLFW_KEY_KP_8:
    return misc::Event::ScanCode::NumericKeypad8;
  case GLFW_KEY_KP_9:
    return misc::Event::ScanCode::NumericKeypad9;
  case GLFW_KEY_KP_DECIMAL:
    return misc::Event::ScanCode::NumericKeypadDecimal;
  case GLFW_KEY_KP_DIVIDE:
    return misc::Event::ScanCode::NumericKeypadDivide;
  case GLFW_KEY_KP_ENTER:
    return misc::Event::ScanCode::NumericKeypadEnter;
  case GLFW_KEY_KP_EQUAL:
    return misc::Event::ScanCode::NumericKeypadEquals;
  case GLFW_KEY_KP_SUBTRACT:
    return misc::Event::ScanCode::NumericKeypadMinus;
  case GLFW_KEY_KP_MULTIPLY:
    return misc::Event::ScanCode::NumericKeypadMultiply;
  case GLFW_KEY_KP_ADD:
    return misc::Event::ScanCode::NumericKeypadPlus;
  case GLFW_KEY_LEFT_ALT:
    return misc::Event::ScanCode::LeftAlt;
  case GLFW_KEY_LEFT_CONTROL:
    return misc::Event::ScanCode::LeftCtrl;
  case GLFW_KEY_LEFT:
    return misc::Event::ScanCode::Left;
  case GLFW_KEY_LEFT_BRACKET:
    return misc::Event::ScanCode::LeftBracket;
  case GLFW_KEY_LEFT_SUPER:
    return misc::Event::ScanCode::LeftGui;
  case GLFW_KEY_LEFT_SHIFT:
    return misc::Event::ScanCode::LeftShift;
  case GLFW_KEY_MENU:
    return misc::Event::ScanCode::Menu;
  case GLFW_KEY_MINUS:
    return misc::Event::ScanCode::Minus;
  case GLFW_KEY_NUM_LOCK:
    return misc::Event::ScanCode::NumLock;
  case GLFW_KEY_PAGE_DOWN:
    return misc::Event::ScanCode::PageDown;
  case GLFW_KEY_PAGE_UP:
    return misc::Event::ScanCode::PageUp;
  case GLFW_KEY_PAUSE:
    return misc::Event::ScanCode::Pause;
  case GLFW_KEY_PERIOD:
    return misc::Event::ScanCode::Period;
  case GLFW_KEY_PRINT_SCREEN:
    return misc::Event::ScanCode::PrintScreen;
  case GLFW_KEY_RIGHT_ALT:
    return misc::Event::ScanCode::RightAlt;
  case GLFW_KEY_RIGHT_CONTROL:
    return misc::Event::ScanCode::RightCtrl;
  case GLFW_KEY_ENTER:
    return misc::Event::ScanCode::Enter;
  case GLFW_KEY_RIGHT_SUPER:
    return misc::Event::ScanCode::RightGui;
  case GLFW_KEY_RIGHT:
    return misc::Event::ScanCode::Right;
  case GLFW_KEY_RIGHT_BRACKET:
    return misc::Event::ScanCode::RightBracket;
  case GLFW_KEY_RIGHT_SHIFT:
    return misc::Event::ScanCode::RightShift;
  case GLFW_KEY_SCROLL_LOCK:
    return misc::Event::ScanCode::ScrollLock;
  case GLFW_KEY_SEMICOLON:
    return misc::Event::ScanCode::Semicolon;
  case GLFW_KEY_SLASH:
    return misc::Event::ScanCode::Slash;
  case GLFW_KEY_SPACE:
    return misc::Event::ScanCode::Space;
  case GLFW_KEY_TAB:
    return misc::Event::ScanCode::Tab;
  case GLFW_KEY_UP:
    return misc::Event::ScanCode::Up;
  default:
    return misc::Event::ScanCode::None;
  }
}
} // namespace gp::sdl::internal
