name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        preset: [vs2022, ninja, emscripten, xcode]
        include:
          - os: windows-latest
            preset: ninja
        exclude:
          - os: ubuntu-latest
            preset: ninja
          - os: ubuntu-latest
            preset: emscripten
          - os: macos-latest
            preset: ninja
          - os: macos-latest
            preset: emscripten
          - os: macos-latest
            preset: xcode
          - os: windows-latest
            preset: vs2022
          - os: ubuntu-latest
            preset: vs2022
          - os: ubuntu-latest
            preset: xcode
          - os: macos-latest
            preset: vs2022
          - os: windows-latest
            preset: xcode
          - os: windows-latest
            preset: emscripten

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Install system dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y nasm
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install nasm
          elif [ "$RUNNER_OS" == "Windows" ]; then
            # NASM is usually available or vcpkg handles it
            echo "NASM handling on Windows..."
          fi
        shell: bash

      - name: Setup Emscripten
        if: matrix.preset == 'emscripten'
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

          # Set EMSDK environment variable for all subsequent steps
          echo "EMSDK=$PWD" >> $GITHUB_ENV

          # Source the environment and export variables
          source ./emsdk_env.sh

          # Make emcc available in PATH
          echo "$PWD/upstream/emscripten" >> $GITHUB_PATH

          # Verify installation
          which emcc
          emcc --version
        shell: bash

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v6

      - name: Set reusable strings
        id: strings
        shell: bash
        run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.preset }}
          buildPreset: ${{ matrix.preset }}
